import streamlit as st
import requests
import subprocess
import socket
import time
import os
import sys
import html
from typing import Dict, Any, List, Optional
from fpdf import FPDF

# Page config
st.set_page_config(
    page_title="DOCURAG - AI Document Assistant",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# API Endpoint URL
BACKEND_URL = "http://127.0.0.1:8000"

# --- PDF GENERATOR UTILITY ---
class ChatPDF(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 15)
        self.set_text_color(99, 102, 241)  # Indigo #6366F1
        self.cell(0, 10, 'DOCURAG - Q&A Chat History Export', border=False, ln=True, align='L')
        self.set_draw_color(226, 232, 240)  # Light gray divider
        self.line(10, 20, 200, 20)
        self.ln(10)
         
    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} | Generated by DOCURAG', align='C')

def export_chat_to_pdf(messages: List[Dict[str, Any]]) -> bytes:
    pdf = ChatPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    for idx, msg in enumerate(messages):
        role = msg["role"]
        content = msg["content"]
        
        # Header block
        pdf.set_font('helvetica', 'B', 11)
        if role == "user":
            pdf.set_text_color(30, 41, 59)  # Slate 800
            pdf.cell(0, 8, f'User Question {idx//2 + 1}:', ln=True)
        else:
            pdf.set_text_color(99, 102, 241)  # Indigo
            pdf.cell(0, 8, f'Grounded Answer {idx//2 + 1}:', ln=True)
             
        # Content
        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(51, 65, 85)  # Slate 700
        clean_content = content.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 5, clean_content)
        
        # Sources block
        if role == "assistant" and msg.get("sources"):
            pdf.ln(2)
            pdf.set_font('helvetica', 'I', 9)
            pdf.set_text_color(100, 116, 139)  # Slate 500
            pdf.cell(0, 5, "Sources Used:", ln=True)
            
            for src_idx, src in enumerate(msg["sources"]):
                if isinstance(src, dict):
                    file_info = src.get('source_doc', 'Unknown Document')
                    chunk_text = src.get('chunk', '')[:120].strip() + "..."
                    confidence = src.get('confidence', 'Unknown')
                else:
                    file_info = "Document Reference"
                    chunk_text = str(src)[:120].strip() + "..."
                    confidence = "Unknown"
                
                clean_ref = f"  [{src_idx+1}] File: {file_info} | Confidence: {confidence} | Text: {chunk_text}"
                clean_ref_encoded = clean_ref.encode('latin-1', 'replace').decode('latin-1')
                pdf.multi_cell(0, 4, clean_ref_encoded)
         
        pdf.ln(8)
    return bytes(pdf.output())

# --- UTILITY TO ENSURE BACKEND IS RUNNING ---
def is_port_open(port: int) -> bool:
    """Check if a specific local port is active."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(('127.0.0.1', port)) == 0

def start_backend_server():
    """Starts the FastAPI backend using uvicorn in a background process if not already running."""
    if not is_port_open(8000):
        with st.spinner("Initializing DOCURAG Core Backend Engine..."):
            python_bin = sys.executable
            logger_env = os.environ.copy()
            logger_env["PYTHONUNBUFFERED"] = "1"
            
            subprocess.Popen(
                [python_bin, "-m", "uvicorn", "app.backend.main:app", "--host", "127.0.0.1", "--port", "8000"],
                env=logger_env,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL
            )
            
            # Poll /health endpoint
            max_retries = 30
            for i in range(max_retries):
                try:
                    res = requests.get(f"{BACKEND_URL}/health", timeout=1)
                    if res.status_code == 200:
                        break
                except requests.exceptions.RequestException:
                    pass
                time.sleep(0.5)
            else:
                st.error("Could not establish connection to backend server. Please refresh or run python run.py manually.")
                st.stop()

# Auto-start backend
start_backend_server()

# --- CSS STYLING OVERRIDES ---
st.markdown("""
<style>
    /* CSS Styles for Glassmorphic Header & Chat Cards */
    .main-header {
        background: rgba(30, 41, 59, 0.4);
        backdrop-filter: blur(12px);
        -webkit-backdrop-filter: blur(12px);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 16px;
        padding: 2rem;
        text-align: center;
        margin-bottom: 2rem;
        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
    }
    .header-title {
        background: linear-gradient(135deg, #a5b4fc 0%, #6366f1 50%, #c084fc 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-size: 2.8rem;
        font-weight: 800;
        letter-spacing: -0.05rem;
        margin: 0;
    }
    .header-subtitle {
        color: #94a3b8;
        font-size: 1.1rem;
        margin-top: 0.5rem;
        margin-bottom: 0;
        font-weight: 400;
    }
    .source-container {
        border-left: 3px solid #6366f1;
        background-color: rgba(99, 102, 241, 0.04);
        padding: 10px 15px;
        border-radius: 0 8px 8px 0;
        margin-bottom: 12px;
        font-size: 0.9rem;
    }
    .source-index {
        font-weight: 700;
        color: #818cf8;
        font-size: 0.8rem;
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }
    .source-text {
        font-style: italic;
        color: #cbd5e1;
        margin-top: 4px;
    }
    .status-badge {
        padding: 4px 10px;
        border-radius: 12px;
        font-size: 0.8rem;
        font-weight: 600;
        display: inline-block;
        margin-top: 5px;
    }
    .status-active {
        background-color: rgba(34, 197, 94, 0.15);
        color: #4ade80;
        border: 1px solid rgba(34, 197, 94, 0.3);
    }
    .status-inactive {
        background-color: rgba(239, 68, 68, 0.15);
        color: #f87171;
        border: 1px solid rgba(239, 68, 68, 0.3);
    }
    /* Technical metrics card styling */
    .metric-card {
        background: rgba(30, 41, 59, 0.6);
        border: 1px solid rgba(255, 255, 255, 0.05);
        border-radius: 8px;
        padding: 12px 10px;
        text-align: center;
        box-shadow: 0 2px 8px rgba(0,0,0,0.15);
    }
    .metric-value {
        font-size: 1.4rem;
        font-weight: 800;
        color: #a5b4fc;
    }
    .metric-label {
        font-size: 0.75rem;
        color: #94a3b8;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        margin-top: 2px;
    }
</style>
""", unsafe_allow_html=True)

# Fetch backend state
def get_backend_status(session_id: Optional[str] = None) -> Dict[str, Any]:
    try:
        url = f"{BACKEND_URL}/status"
        if session_id:
            url += f"?session_id={session_id}"
        response = requests.get(url)
        if response.status_code == 200:
            return response.json()
    except Exception:
        pass
    return {
        "document_loaded": False,
        "chunks_count": 0,
        "indexed_documents": [],
        "gemini_api_key_configured": False,
        "embedding_model": "all-MiniLM-L6-v2"
    }

# Initialize session state variables
import uuid
if "session_id" not in st.session_state:
    st.session_state.session_id = str(uuid.uuid4())
if "messages" not in st.session_state:
    st.session_state.messages = []
if "uploaded_filename" not in st.session_state:
    st.session_state.uploaded_filename = None
if "active_summary" not in st.session_state:
    st.session_state.active_summary = None
if "active_analytics" not in st.session_state:
    st.session_state.active_analytics = None

backend_status = get_backend_status(st.session_state.session_id)

# Fetch all saved sessions from backend database
def get_saved_sessions() -> List[Dict[str, Any]]:
    try:
        res = requests.get(f"{BACKEND_URL}/sessions")
        if res.status_code == 200:
            return res.json()
    except Exception:
        pass
    return []

# --- SIDEBAR: SETTINGS & FILES ---
with st.sidebar:
    st.image("https://img.icons8.com/isometric/100/database.png", width=60)
    st.title("DOCURAG Panel")
    
    # Session Management
    st.markdown("---")
    st.subheader("💬 Chat Sessions")
    saved_sessions = get_saved_sessions()
    
    # Start New Chat Button
    if st.button("➕ Start New Chat", use_container_width=True):
        st.session_state.session_id = str(uuid.uuid4())
        st.session_state.uploaded_filename = None
        st.session_state.messages = []
        st.session_state.active_summary = None
        st.session_state.active_analytics = None
        st.rerun()

    if saved_sessions:
        session_ids = [s["session_id"] for s in saved_sessions]
        session_labels = [
            f"📄 {s['document_name'] or 'General Chat'} ({s['created_at'][11:16]} - {s['created_at'][5:10]})"
            for s in saved_sessions
        ]
        
        # Calculate current session index in dropdown
        current_index = None
        if st.session_state.session_id in session_ids:
            current_index = session_ids.index(st.session_state.session_id)
            
        selected_label = st.selectbox(
            "Load History",
            options=session_labels,
            index=current_index,
            placeholder="Select a previous session...",
            key="session_select_widget"
        )
        
        if selected_label:
            idx = session_labels.index(selected_label)
            selected_id = session_ids[idx]
            if selected_id != st.session_state.session_id:
                st.session_state.session_id = selected_id
                # Fetch messages and analytics for this session
                try:
                    res = requests.get(f"{BACKEND_URL}/sessions/{selected_id}/messages")
                    if res.status_code == 200:
                        st.session_state.messages = res.json()
                        st.session_state.uploaded_filename = saved_sessions[idx]["document_name"]
                        st.session_state.active_summary = saved_sessions[idx].get("summary")
                        
                        # Load analytics
                        import json
                        anal_str = saved_sessions[idx].get("analytics")
                        if anal_str:
                            st.session_state.active_analytics = json.loads(anal_str)
                        else:
                            st.session_state.active_analytics = None
                        st.rerun()
                except Exception as e:
                    st.error(f"Failed to load chat history: {e}")
                    
        # Option to delete current session
        if st.button("🗑️ Delete Selected Chat", use_container_width=True):
            try:
                requests.delete(f"{BACKEND_URL}/sessions/{st.session_state.session_id}")
                st.session_state.session_id = str(uuid.uuid4())
                st.session_state.uploaded_filename = None
                st.session_state.messages = []
                st.session_state.active_summary = None
                st.session_state.active_analytics = None
                st.rerun()
            except Exception as e:
                st.error(f"Failed to delete session: {e}")

    st.markdown("---")
    
    # 1. API Configuration
    st.subheader("🔑 Gemini API Settings")
    api_key_env = os.getenv("GEMINI_API_KEY", "")
    
    if "api_key" not in st.session_state:
        st.session_state.api_key = api_key_env
        
    api_key_input = st.text_input(
        "Enter Gemini API Key",
        value=st.session_state.api_key,
        type="password",
        help="Obtain a free key from Google AI Studio."
    )
    
    if api_key_input != st.session_state.api_key:
        st.session_state.api_key = api_key_input
        try:
            requests.post(f"{BACKEND_URL}/configure", json={"gemini_api_key": api_key_input})
        except Exception:
            pass

    is_api_ready = bool(st.session_state.api_key.strip())
    if is_api_ready:
        st.markdown('<div class="status-badge status-active">● Gemini API Configured</div>', unsafe_allow_html=True)
    else:
        st.markdown('<div class="status-badge status-inactive">▲ API Key Required</div>', unsafe_allow_html=True)

    st.markdown("---")
    
    # 2. File Upload
    st.subheader("📁 Upload Document")
    uploaded_file = st.file_uploader(
        "Upload Document (PDF, TXT, DOCX, HTML, MD)",
        type=["pdf", "txt", "docx", "html", "htm", "md"],
        help="Upload a document to append to this session's FAISS index."
    )
    
    # 3. Tuning Hyperparameters
    st.subheader("⚙️ Index Configurations")
    chunk_size = st.slider("Chunk Size (Characters)", min_value=100, max_value=1500, value=500, step=50)
    chunk_overlap = st.slider("Overlap (Characters)", min_value=0, max_value=400, value=50, step=10)
    top_k = st.slider("Retrieval Count (Top K)", min_value=1, max_value=10, value=4)
    
    if chunk_overlap >= chunk_size:
        st.error("Overlap must be smaller than Chunk Size!")
        
    st.markdown("---")

    # Document upload button execution
    if uploaded_file is not None and (st.session_state.uploaded_filename is None or uploaded_file.name not in st.session_state.uploaded_filename):
        with st.spinner(f"Processing & Analyzing '{uploaded_file.name}'..."):
            files = {"file": (uploaded_file.name, uploaded_file.getvalue(), uploaded_file.type)}
            params = {
                "session_id": st.session_state.session_id,
                "chunk_size": chunk_size,
                "chunk_overlap": chunk_overlap
            }
            try:
                res = requests.post(f"{BACKEND_URL}/upload", files=files, params=params)
                if res.status_code == 200:
                    data = res.json()
                    st.success(f"Indexed! Added {data['chunks_count']} chunks.")
                    st.session_state.uploaded_filename = data["filename"] if st.session_state.uploaded_filename is None else f"{st.session_state.uploaded_filename}, {uploaded_file.name}"
                    st.session_state.active_summary = data.get("summary")
                    st.session_state.active_analytics = data.get("analytics")
                    st.session_state.messages = []
                    st.rerun()
                else:
                    st.error(f"Failed to process document: {res.json().get('detail', 'Unknown error')}")
            except Exception as e:
                st.error(f"Error connecting to backend upload: {str(e)}")

    # Display Session Document details and exports
    if backend_status.get("document_loaded"):
        docs_list = backend_status.get("indexed_documents", [])
        if docs_list:
            docs_rendered = "\n".join([f"- `{doc}`" for doc in docs_list])
            st.markdown(f"**Indexed Documents:**\n{docs_rendered}")
            
        # Display custom metrics grid
        st.subheader("📊 Session Statistics")
        c_count = backend_status.get("chunks_count", 0)
        
        # Calculate read time if analytics exist
        read_time_str = "N/A"
        if st.session_state.active_analytics:
            w_count = st.session_state.active_analytics.get("word_count", 0)
            read_time_str = f"~{max(1, round(w_count / 200))} min"
            
        st.markdown(f"""
        <div style="display: flex; gap: 8px; margin-bottom: 15px; flex-wrap: wrap;">
            <div class="metric-card" style="flex: 1; min-width: 70px; padding: 8px 5px;">
                <div class="metric-value" style="font-size: 1.1rem;">{c_count}</div>
                <div class="metric-label" style="font-size: 0.65rem;">Chunks</div>
            </div>
            <div class="metric-card" style="flex: 1; min-width: 70px; padding: 8px 5px;">
                <div class="metric-value" style="font-size: 1.1rem;">{int(c_count * 125):,}</div>
                <div class="metric-label" style="font-size: 0.65rem;">Tokens</div>
            </div>
            <div class="metric-card" style="flex: 1; min-width: 70px; padding: 8px 5px;">
                <div class="metric-value" style="font-size: 1.1rem; color: #38bdf8;">{read_time_str}</div>
                <div class="metric-label" style="font-size: 0.65rem;">Read Time</div>
            </div>
        </div>
        """, unsafe_allow_html=True)
            
        st.markdown("---")
        
        # PDF Exporter Button
        if st.session_state.messages:
            st.subheader("📥 Export Conversation")
            pdf_bytes = export_chat_to_pdf(st.session_state.messages)
            st.download_button(
                label="📄 Download Chat PDF",
                data=pdf_bytes,
                file_name=f"chat_export_{st.session_state.session_id[:8]}.pdf",
                mime="application/pdf",
                use_container_width=True
            )
            st.markdown("---")

        # Clear Index Action
        if st.button("🗑️ Clear Session Index"):
            st.session_state.uploaded_filename = None
            st.session_state.messages = []
            st.session_state.active_summary = None
            st.session_state.active_analytics = None
            try:
                requests.delete(f"{BACKEND_URL}/sessions/{st.session_state.session_id}")
            except Exception:
                pass
            st.rerun()
    else:
        st.warning("No documents indexed yet. Upload a document (PDF, TXT, DOCX, HTML, MD) to start.")

# --- MAIN APP VIEW ---

# Header block
st.markdown("""
<div class="main-header">
    <h1 class="header-title">DOCURAG</h1>
    <p class="header-subtitle">Intelligent Document QA Assistant (PDF, TXT, DOCX, HTML, MD) Powered by Gemini & FAISS</p>
</div>
""", unsafe_allow_html=True)

# Helper function to submit query
def execute_query(prompt_text: str):
    # 1. User Message
    st.session_state.messages.append({"role": "user", "content": prompt_text})
    
    # We make the API call
    history_payload = [
        {"role": msg["role"], "content": msg["content"]} 
        for msg in st.session_state.messages[:-1]
    ]
    
    payload = {
        "query": prompt_text,
        "session_id": st.session_state.session_id,
        "history": history_payload,
        "top_k": top_k,
        "gemini_api_key": st.session_state.api_key
    }
    
    try:
        res = requests.post(f"{BACKEND_URL}/query", json=payload)
        if res.status_code == 200:
            result = res.json()
            answer = result["answer"]
            sources = result["sources"]
            saved_sources = [dict(s) for s in sources]
            st.session_state.messages.append({
                "role": "assistant",
                "content": answer,
                "sources": saved_sources
            })
        else:
            st.error(f"Error querying assistant: {res.json().get('detail', 'Unknown error')}")
    except Exception as e:
        st.error(f"Could not connect to backend server: {str(e)}")

# --- WOW FEATURE: SMART DOCUMENT INSIGHTS DASHBOARD ---
if st.session_state.active_analytics:
    anal = st.session_state.active_analytics
    
    # Topics pills generation
    topics_html = ""
    for topic in anal.get("key_topics", []):
        topics_html += f"""
        <span style="
            background-color: rgba(99, 102, 241, 0.12);
            color: #a5b4fc;
            border: 1px solid rgba(99, 102, 241, 0.25);
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.82rem;
            font-weight: 600;
            display: inline-block;
            margin: 4px;
        ">
            🏷️ {topic}
        </span>
        """
        
    st.markdown(f"""
    <div style="
        background: rgba(30, 41, 59, 0.4);
        backdrop-filter: blur(8px);
        -webkit-backdrop-filter: blur(8px);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 12px;
        padding: 20px;
        margin-bottom: 25px;
        box-shadow: 0 4px 20px rgba(0,0,0,0.15);
    ">
        <div style="font-weight: 700; color: #818cf8; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 12px; display: flex; align-items: center; gap: 6px;">
            <span>📊</span> Smart Document Insights (Session Analytics)
        </div>
        
        <!-- Stats Row -->
        <div style="display: flex; gap: 12px; margin-bottom: 18px; flex-wrap: wrap;">
            <div class="metric-card" style="flex: 1; min-width: 90px;">
                <div class="metric-value">{anal.get('page_count', 1)}</div>
                <div class="metric-label">Pages</div>
            </div>
            <div class="metric-card" style="flex: 1; min-width: 90px;">
                <div class="metric-value">{anal.get('word_count', 0):,}</div>
                <div class="metric-label">Words</div>
            </div>
            <div class="metric-card" style="flex: 1; min-width: 90px;">
                <div class="metric-value" style="color: #38bdf8;">~{max(1, round(anal.get('word_count', 0) / 200))} min</div>
                <div class="metric-label">Read Time</div>
            </div>
            <div class="metric-card" style="flex: 1; min-width: 90px;">
                <div class="metric-value">{backend_status.get('chunks_count', 0)}</div>
                <div class="metric-label">Chunks</div>
            </div>
            <div class="metric-card" style="flex: 1; min-width: 90px;">
                <div class="metric-value">{int(backend_status.get('chunks_count', 0) * 125):,}</div>
                <div class="metric-label">Est. Tokens</div>
            </div>
        </div>
        
        <!-- Topics Row -->
        <div style="margin-bottom: 18px;">
            <div style="font-size: 0.78rem; color: #94a3b8; font-weight: 700; text-transform: uppercase; letter-spacing: 0.03em; margin-bottom: 8px;">Key Extracted Topics</div>
            <div>{topics_html}</div>
        </div>
        
        <!-- Auto Summary Row -->
        {f'''<div style="border-top: 1px solid rgba(255, 255, 255, 0.06); padding-top: 15px;">
            <div style="font-size: 0.78rem; color: #94a3b8; font-weight: 700; text-transform: uppercase; letter-spacing: 0.03em; margin-bottom: 8px;">3-Line Executive Summary</div>
            <div style="font-size: 0.95rem; color: #cbd5e1; line-height: 1.5; font-style: normal;">{st.session_state.active_summary.replace('- ', '• ')}</div>
        </div>''' if st.session_state.active_summary else ''}
    </div>
    """, unsafe_allow_html=True)

# Render Chat History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        
        if message["role"] == "assistant":
            # Copy Button HTML
            escaped_text = html.escape(message["content"]).replace("`", "\\`").replace("$", "\\$")
            copy_button_html = f"""
            <button onclick="navigator.clipboard.writeText(`{escaped_text}`); this.innerText='📋 Copied!';" style="
                background-color: rgba(255, 255, 255, 0.05);
                color: #cbd5e1;
                border: 1px solid rgba(255, 255, 255, 0.1);
                border-radius: 4px;
                padding: 4px 10px;
                font-size: 0.75rem;
                cursor: pointer;
                display: inline-flex;
                align-items: center;
                gap: 4px;
                margin-top: 8px;
                margin-bottom: 12px;
            ">
                📋 Copy Answer
            </button>
            """
            st.markdown(copy_button_html, unsafe_allow_html=True)
            
            # Citation blocks
            if message.get("sources"):
                with st.expander("🔍 Verified Source Citations"):
                    for idx, src in enumerate(message["sources"]):
                        if isinstance(src, dict):
                            chunk_text = src.get("chunk", "")
                            source_doc = src.get("source_doc", "Unknown File")
                            confidence = src.get("confidence", "Medium")
                        else:
                            chunk_text = str(src)
                            source_doc = "Reference Block"
                            confidence = "Medium"
                            
                        # Confidence Badge Styling
                        if confidence == "High":
                            badge_color = "rgba(34, 197, 94, 0.12)"
                            badge_text = "#4ade80"
                            badge_border = "rgba(34, 197, 94, 0.25)"
                        elif confidence == "Medium":
                            badge_color = "rgba(245, 158, 11, 0.12)"
                            badge_text = "#fbbf24"
                            badge_border = "rgba(245, 158, 11, 0.25)"
                        else:
                            badge_color = "rgba(239, 68, 68, 0.12)"
                            badge_text = "#f87171"
                            badge_border = "rgba(239, 68, 68, 0.25)"
                            
                        st.markdown(
                            f"""<div class="source-container">
                                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px;">
                                    <div class="source-index">Reference {idx+1} (from: {source_doc})</div>
                                    <span style="background-color: {badge_color}; color: {badge_text}; border: 1px solid {badge_border}; font-size: 0.7rem; font-weight: 700; padding: 2px 6px; border-radius: 4px;">{confidence} Match</span>
                                </div>
                                <div class="source-text">"{chunk_text}"</div>
                            </div>""", 
                            unsafe_allow_html=True
                        )

# Clickable Suggested Questions (Shown only when chat history is empty)
if st.session_state.active_analytics and not st.session_state.messages:
    st.markdown("### 💡 Suggested Questions to Get Started")
    questions = st.session_state.active_analytics.get("suggested_questions", [])
    
    # Render suggested questions as columns of button cards
    cols = st.columns(len(questions))
    for q_idx, q in enumerate(questions):
        # Clean button text slightly
        q_label = q.strip()
        if cols[q_idx].button(f"❓ {q_label}", key=f"suggested_q_{q_idx}", use_container_width=True):
            execute_query(q_label)
            st.rerun()

# Accept standard Chat Input
if prompt := st.chat_input("Ask a question about the uploaded documents..."):
    execute_query(prompt)
    st.rerun()
